version: '3.1'

services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./flashcards.js:/docker-entrypoint-initdb.d/flashcards.js:ro
    ports:
      - ${MONGODB_PORT}:27017

  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    depends_on:
      - mongodb

volumes: 
  mongo_db: {}