POST http://127.0.0.1:43808/message/send HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWVhNzg0ZWRkY2YwMmU0Y2IwMTA4OGIiLCJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImlhdCI6MTcxMDg4NTc5MywiZXhwIjoxNzEwOTcyMTkzfQ.GDuK9-BzvfenDnBebNG7dzhxuaSfM4GFaCucNoMsbXY

{
  "to": "65f8df462354c3fb2897deb2",
  "message": {
    "from": "65ea784dedcf02e4cb01088b",
    "text": "Hello, this is a message from 'daniel' to 'test2'!"
  }
}

