GET http://127.0.0.1:43808/user/info HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWVhNzg0ZWRkY2YwMmU0Y2IwMTA4OGIiLCJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImlhdCI6MTcxMDE2OTQ4NCwiZXhwIjoxNzEwMjU1ODg0fQ.hGX5m328UMuCuqgfy6wZh_PJ8mb6M3IAiKje1apycM4

# DON'T PROVIDE BODY