GET http://127.0.0.1:43808/user/info HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjAwODA5M2NmN2U3ZjE3MWQwNzc0N2YiLCJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImlhdCI6MTcxMTMwODk2MSwiZXhwIjoxNzExMzk1MzYxfQ.VJI2r3wFcSxqUbVJKRK31deUMt9bsz33brZw-ls8rIs

###

GET http://127.0.0.1:43808/user/flashcards HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWVhNzg0ZWRkY2YwMmU0Y2IwMTA4OGIiLCJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImlhdCI6MTcxMDgwOTA5MCwiZXhwIjoxNzEwODk1NDkwfQ.zKLApeZbK5DvoNXCQfyh__DqO3mng9sG6oWAzCziXig

###

DELETE http://127.0.0.1:43808/user/deleteAccount HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWVhNzg0ZWRkY2YwMmU0Y2IwMTA4OGIiLCJ1c2VybmFtZSI6ImRhbmllbCIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImlhdCI6MTcxMTIzNjUzOSwiZXhwIjoxNzExMzIyOTM5fQ.jvEpybgZo20hEqlmNKQ1ylS9ESHDBvAVxaeXXhWmAGk

# main.users.json